// Code generated by "stringer -type=RedBlackTreeColor -linecomment"; DO NOT EDIT.

package verifier

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RedBlackTreeColor_Red-128]
	_ = x[RedBlackTreeColor_Black-129]
}

const _RedBlackTreeColor_name = "RedBlk"

var _RedBlackTreeColor_index = [...]uint8{0, 3, 6}

func (i RedBlackTreeColor) String() string {
	i -= 128
	if i >= RedBlackTreeColor(len(_RedBlackTreeColor_index)-1) {
		return "RedBlackTreeColor(" + strconv.FormatInt(int64(i+128), 10) + ")"
	}
	return _RedBlackTreeColor_name[_RedBlackTreeColor_index[i]:_RedBlackTreeColor_index[i+1]]
}
