// Code generated by "stringer -type=TreeType -linecomment"; DO NOT EDIT.

package verifier

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TreeType_Vanilla-0]
	_ = x[TreeType_RedBlack-1]
	_ = x[TreeType_Avl-2]
}

const _TreeType_name = "VanilaRedBlackAVL"

var _TreeType_index = [...]uint8{0, 6, 14, 17}

func (i TreeType) String() string {
	if i >= TreeType(len(_TreeType_index)-1) {
		return "TreeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TreeType_name[_TreeType_index[i]:_TreeType_index[i+1]]
}
